services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: rag_pgvector_db
    environment:
      POSTGRES_USER: rag_user
      POSTGRES_PASSWORD: rag_password
      POSTGRES_DB: rag_db
    ports:
      - "5432:5432"
    volumes:
      - rag_pgvector_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: rag_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres

volumes:
  rag_pgvector_data: